### PR TITLE
Add basic RBS generation support, generalised types, and tree conversion

### PR DESCRIPTION
**Pull request by AaronC81**
This branch is released under "5.0.0.beta.x" for ease of testing. Install with `gem install parlour --pre`.

-----

This PR adds the basics of RBS generation support to Parlour.

Notable additions include:

  - `RbsGenerator`, which is the "entry point" for generation, like `RbiGenerator` 
  - `RbsObject` and its subclasses, which are the nodes of the tree
  - `Types`, which provides a common description of types across type systems. These types can be generated into RBI or RBS, and will eventually replace legacy RBI string types. (For now, functions accept a `Types::TypeLike`, which can be either a `Types::Type` or a string.)
  - `RbiObject#generalize_from_rbi!`, which parses an RBI type tree's legacy string types into `Types` types.
  - `Conversion::Converter`, which provides a base for conversion between different type trees.
  - `Conversion::RbiToRbs`, which converts from `RbiObject`s to `RbsObject`s.

If you'd like to test this out, setting the experimental environment variable `PARLOUR_CONVERT_TO_RBS=` will force existing plugins and tools which generate an RBI to generate an RBS instead. You can verify if an RBS is valid using the [RBS command-line tool](https://github.com/ruby/rbs#cli).

This is a _gigantic_ addition to Parlour, so any reviews at all are greatly appreciated!

### CODE REVIEW

**Comment by manhhung741** [comment]
Thanks for putting this PR together so quickly. It'd be useful to have a doc documenting the RBS types and start documenting differences between RBI and RBS that you found (or have worked through). 

Haven't reviewed it carefully, but I saw a note about RBS not supporting struct. If it's T::Struct, I can see a 1-way conversion here where a T::Struct can be represented as a normal class

```
class A < T::Struct
  prop :a, String
end
```
is the same as the following in RBS:
```
class A
  attr_accessor a: String
end
```

**Comment by AaronC81** [comment]
@manhhung741 Good idea, I hadn't considered just doing a conversion to a class! I'll look into that for enums too.

Don't worry, I'll definitely end up (re)writing a lot of documentation for this - quite a lot of existing docs will probably end up being changed a bit (since Parlour is no longer just an RBI generator/parser), and I'll write new docs about RBS and conversion.

**Comment by manhhung741** [comment]
I think if there are _some_ doc as part of this PR, it may be easier to
review it. Mainly because not everyone is familiar with RBS. By
documenting, you can help us gathering context needed to understand the
code.

**Comment by AaronC81** [comment]
Great point - thanks for all your feedback so far. I'll work on adding some docs later today :smiley:

**Comment by AaronC81** [comment]
I've updated the README with quite a bit more info, and also added a wiki page about `Parlour::Types`.

**Pull request merged**
